DELIMITER $$

USE `Jurisdiction`$$

DROP PROCEDURE IF EXISTS `DELNODE_CALL`$$

CREATE DEFINER=`XT_RN`@`%` PROCEDURE `DELNODE_CALL`(IN nodeId  INT,OUT v_msg  VARCHAR(20))
BEGIN
	  DELETE FROM  ROLE_NODE WHERE NODE_ID IN (SELECT NODE_ID  FROM  NODE WHERE  NODE_PID IN ( SELECT NODE_ID FROM NODE WHERE NODE_PID = nodeId)  OR  NODE_ID =nodeId  OR NODE_PID=nodeId);
         
          DELETE FROM  NODE WHERE NODE_PID IN  (SELECT t.NODE_ID FROM(SELECT NODE_ID FROM NODE WHERE NODE_PID = nodeId)t)  OR  NODE_ID =nodeId OR NODE_PID=nodeId;
          SET v_msg='删除成功';
    END$$

DELIMITER ;