DELIMITER $$


DROP FUNCTION IF EXISTS `SPLIT`$$

CREATE  FUNCTION `SPLIT`(str VARCHAR(4000),delim VARCHAR(16), n INT) RETURNS VARCHAR(255) CHARSET utf8
BEGIN
        DECLARE str1 NVARCHAR(255);
	DECLARE str2 NVARCHAR(255);
    
        IF n <= 1 THEN 
		RETURN SUBSTRING_INDEX(SUBSTRING_INDEX(str, delim, n), delim, -1);
	ELSE
		SET str1 = SUBSTRING_INDEX(SUBSTRING_INDEX(str, delim, n-1), delim, -1);
		SET str2 = SUBSTRING_INDEX(SUBSTRING_INDEX(str, delim, n), delim, -1);
		IF STRCMP(str1, str2) <> 0 THEN
			RETURN str2;
		ELSE
			RETURN "";
		END IF;
	END IF;
    END$$

DELIMITER ;